
package com.ITtexn.pz4.client.film_cl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilmService", targetNamespace = "http://film.service.pz4.ITtexn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilmService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     */
    @WebMethod
    @RequestWrapper(localName = "updateFilm", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.UpdateFilm")
    @ResponseWrapper(localName = "updateFilmResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.UpdateFilmResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/updateFilmRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/updateFilmResponse")
    public void updateFilm(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Genre arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @return
     *     returns java.util.List<com.ITtexn.pz4.client.film_cl.Film>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFilms", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.GetAllFilms")
    @ResponseWrapper(localName = "getAllFilmsResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.GetAllFilmsResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/getAllFilmsRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/getAllFilmsResponse")
    public List<Film> getAllFilms();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ITtexn.pz4.client.film_cl.Film
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilm", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.GetFilm")
    @ResponseWrapper(localName = "getFilmResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.GetFilmResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/getFilmRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/getFilmResponse")
    public Film getFilm(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countFilms", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.CountFilms")
    @ResponseWrapper(localName = "countFilmsResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.CountFilmsResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/countFilmsRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/countFilmsResponse")
    public int countFilms();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteFilm", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.DeleteFilm")
    @ResponseWrapper(localName = "deleteFilmResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.DeleteFilmResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/deleteFilmRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/deleteFilmResponse")
    public void deleteFilm(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     */
    @WebMethod
    @RequestWrapper(localName = "insertFilm", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.InsertFilm")
    @ResponseWrapper(localName = "insertFilmResponse", targetNamespace = "http://film.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.film_cl.InsertFilmResponse")
    @Action(input = "http://film.service.pz4.ITtexn.com/FilmService/insertFilmRequest", output = "http://film.service.pz4.ITtexn.com/FilmService/insertFilmResponse")
    public void insertFilm(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Genre arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

}
