
package com.ITtexn.pz4.client.session_cl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SessionService", targetNamespace = "http://session.service.pz4.ITtexn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SessionService {


    /**
     * 
     * @return
     *     returns java.util.List<com.ITtexn.pz4.client.session_cl.Session>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSessions", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.GetAllSessions")
    @ResponseWrapper(localName = "getAllSessionsResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.GetAllSessionsResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/getAllSessionsRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/getAllSessionsResponse")
    public List<Session> getAllSessions();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertSession", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.InsertSession")
    @ResponseWrapper(localName = "insertSessionResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.InsertSessionResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/insertSessionRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/insertSessionResponse")
    public void insertSession(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Hall arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Film arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ITtexn.pz4.client.session_cl.Session
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSession", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.GetSession")
    @ResponseWrapper(localName = "getSessionResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.GetSessionResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/getSessionRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/getSessionResponse")
    public Session getSession(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateSession", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.UpdateSession")
    @ResponseWrapper(localName = "updateSessionResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.UpdateSessionResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/updateSessionRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/updateSessionResponse")
    public void updateSession(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Hall arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Film arg4);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSession", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.DeleteSession")
    @ResponseWrapper(localName = "deleteSessionResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.DeleteSessionResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/deleteSessionRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/deleteSessionResponse")
    public void deleteSession(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countSession", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.CountSession")
    @ResponseWrapper(localName = "countSessionResponse", targetNamespace = "http://session.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.session_cl.CountSessionResponse")
    @Action(input = "http://session.service.pz4.ITtexn.com/SessionService/countSessionRequest", output = "http://session.service.pz4.ITtexn.com/SessionService/countSessionResponse")
    public int countSession();

}
