
package com.ITtexn.pz4.client.hall_cl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HallService", targetNamespace = "http://hall.service.pz4.ITtexn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HallService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateHall", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.UpdateHall")
    @ResponseWrapper(localName = "updateHallResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.UpdateHallResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/updateHallRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/updateHallResponse")
    public void updateHall(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countHall", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.CountHall")
    @ResponseWrapper(localName = "countHallResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.CountHallResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/countHallRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/countHallResponse")
    public int countHall();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ITtexn.pz4.client.hall_cl.Hall
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHall", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.GetHall")
    @ResponseWrapper(localName = "getHallResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.GetHallResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/getHallRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/getHallResponse")
    public Hall getHall(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHall", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.DeleteHall")
    @ResponseWrapper(localName = "deleteHallResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.DeleteHallResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/deleteHallRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/deleteHallResponse")
    public void deleteHall(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.ITtexn.pz4.client.hall_cl.Hall>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllHalls", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.GetAllHalls")
    @ResponseWrapper(localName = "getAllHallsResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.GetAllHallsResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/getAllHallsRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/getAllHallsResponse")
    public List<Hall> getAllHalls();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertHall", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.InsertHall")
    @ResponseWrapper(localName = "insertHallResponse", targetNamespace = "http://hall.service.pz4.ITtexn.com/", className = "com.ITtexn.pz4.client.hall_cl.InsertHallResponse")
    @Action(input = "http://hall.service.pz4.ITtexn.com/HallService/insertHallRequest", output = "http://hall.service.pz4.ITtexn.com/HallService/insertHallResponse")
    public void insertHall(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
