
package com.ITtexn.pz4.client.hall_cl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HallServiceImplementService", targetNamespace = "http://hall.service.pz4.ITtexn.com/", wsdlLocation = "http://localhost:7777/hall?wsdl")
public class HallServiceImplementService
    extends Service
{

    private final static URL HALLSERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HALLSERVICEIMPLEMENTSERVICE_EXCEPTION;
    private final static QName HALLSERVICEIMPLEMENTSERVICE_QNAME = new QName("http://hall.service.pz4.ITtexn.com/", "HallServiceImplementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/hall?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HALLSERVICEIMPLEMENTSERVICE_WSDL_LOCATION = url;
        HALLSERVICEIMPLEMENTSERVICE_EXCEPTION = e;
    }

    public HallServiceImplementService() {
        super(__getWsdlLocation(), HALLSERVICEIMPLEMENTSERVICE_QNAME);
    }

    public HallServiceImplementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HALLSERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public HallServiceImplementService(URL wsdlLocation) {
        super(wsdlLocation, HALLSERVICEIMPLEMENTSERVICE_QNAME);
    }

    public HallServiceImplementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HALLSERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public HallServiceImplementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HallServiceImplementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HallService
     */
    @WebEndpoint(name = "HallServiceImplementPort")
    public HallService getHallServiceImplementPort() {
        return super.getPort(new QName("http://hall.service.pz4.ITtexn.com/", "HallServiceImplementPort"), HallService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HallService
     */
    @WebEndpoint(name = "HallServiceImplementPort")
    public HallService getHallServiceImplementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hall.service.pz4.ITtexn.com/", "HallServiceImplementPort"), HallService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HALLSERVICEIMPLEMENTSERVICE_EXCEPTION!= null) {
            throw HALLSERVICEIMPLEMENTSERVICE_EXCEPTION;
        }
        return HALLSERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    }

}
